# Generated by Django 2.0.3 on 2018-03-28 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascii_city_name', models.CharField(max_length=128, verbose_name='Ascii name')),
                ('city_name', models.CharField(max_length=128, verbose_name='Name')),
                ('region', models.CharField(max_length=2, verbose_name='Region')),
                ('population', models.BigIntegerField(verbose_name='pop')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'CC',
                'verbose_name_plural': 'CCs',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CountryCode'),
        ),
    ]
