# Generated by Django 2.0.3 on 2018-03-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrycode',
            old_name='title',
            new_name='code',
        ),
    ]
